# Generated by Django 3.2.16 on 2023-01-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAllProxy',
            fields=[
            ],
            options={
                'verbose_name': 'All Video',
                'verbose_name_plural': 'All Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
