# Generated by Django 3.2.16 on 2023-01-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publish_timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
