# Generated by Django 3.2.16 on 2023-01-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_video_video_id'),
        ('playlists', '0003_auto_20230116_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_playlist', to='videos.video'),
        ),
    ]
