# Generated by Django 3.2.16 on 2023-01-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0013_alter_playlist_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvshowproxy',
            options={'verbose_name': 'TV Show', 'verbose_name_plural': 'TV Shows'},
        ),
        migrations.AlterModelOptions(
            name='tvshowseasonproxy',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
    ]
